steps:
  - name: 'node:20'
    env:
      - HOME=/workspace
    args:
      - '-c'
      - |
        cd frontend &&
        npm install &&
        npm run build &&
        rm -rf public src README.md package-lock.json package.json tsconfig.json
    id: Prepare frontend deploy
    entrypoint: bash
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    env:
      - HOME=/workspace
    args:
      - '-c'
      - |
        cd frontend &&
        gcloud app deploy --quiet
    id: Frontend deploy
    waitFor:
      - Prepare frontend deploy
    entrypoint: bash
options:
  logging: CLOUD_LOGGING_ONLY