steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - gpt-chat-reply
  - --region=europe-west3
  - --source=/backend/gpt-chat-reply
  - --trigger-http
  - --runtime=python311
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - gpt-explain-reply
  - --region=europe-west3
  - --source=/backend/gpt-explain-reply
  - --trigger-http
  - --runtime=python311
