steps:
  - id: Prepare frontend deploy
    name: 'bash'
    script:
      - git clone https://github.com/Starzor/language-learning-app.git
      - cd frontend
      - npm install
      - npm run build
      - rm public
      - rm src
      - rm README.md
      - rm package-lock.json
      - rm package.json
      - rm tsconfig.json
  
  - id: Frontend deploy
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    script:
      - gcloud app deploy --quiet
    waitFor: ['Prepare frontend deploy']