steps:
  - id: Deploy frontend
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', '
      gcloud config set app/cloud_build_timeout 1600 && \
      cd /frontend && \
      npm install && \
      npm run build && \
      gcloud app deploy --quiet
    ']
    timeout: '1600s'