steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:485.0.0'
  args:
  - gcloud
  - functions
  - deploy
  - gpt-chat-reply
  - --region=europe-west3
  - --source=repo=https://source.developers.google.com/projects/gclearning-426207/repos/Starzor-language-learning-app
  - --source-path=/backend/gpt-chat-reply
  - --trigger-http
  - --runtime=python311
    
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:485.0.0'
  args:
  - gcloud
  - functions
  - deploy
  - gpt-explain-reply
  - --region=europe-west3
  - --source=repo=https://source.developers.google.com/projects/gclearning-426207/repos/Starzor-language-learning-app
  - --source-path=/backend/gpt-explain-reply
  - --trigger-http
  - --runtime=python311
options:
  logging: CLOUD_LOGGING_ONLY
